// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock/mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	application "github.com/n1jke/oop-bsuir-2026/laboratory_work-7/internal/application"
	domain "github.com/n1jke/oop-bsuir-2026/laboratory_work-7/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTransactor) WithTransaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTransactorMockRecorder) WithTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTransactor)(nil).WithTransaction), arg0, arg1)
}

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
	isgomock struct{}
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBookRepository) Add(ctx context.Context, book domain.Book) (domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, book)
	ret0, _ := ret[0].(domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBookRepositoryMockRecorder) Add(ctx, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBookRepository)(nil).Add), ctx, book)
}

// GetByID mocks base method.
func (m *MockBookRepository) GetByID(ctx context.Context, bookID uuid.UUID) (domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, bookID)
	ret0, _ := ret[0].(domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookRepositoryMockRecorder) GetByID(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookRepository)(nil).GetByID), ctx, bookID)
}

// GetByTitle mocks base method.
func (m *MockBookRepository) GetByTitle(ctx context.Context, title string) ([]*domain.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTitle", ctx, title)
	ret0, _ := ret[0].([]*domain.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTitle indicates an expected call of GetByTitle.
func (mr *MockBookRepositoryMockRecorder) GetByTitle(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTitle", reflect.TypeOf((*MockBookRepository)(nil).GetByTitle), ctx, title)
}

// MockExchangeRepository is a mock of ExchangeRepository interface.
type MockExchangeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeRepositoryMockRecorder
	isgomock struct{}
}

// MockExchangeRepositoryMockRecorder is the mock recorder for MockExchangeRepository.
type MockExchangeRepositoryMockRecorder struct {
	mock *MockExchangeRepository
}

// NewMockExchangeRepository creates a new mock instance.
func NewMockExchangeRepository(ctrl *gomock.Controller) *MockExchangeRepository {
	mock := &MockExchangeRepository{ctrl: ctrl}
	mock.recorder = &MockExchangeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeRepository) EXPECT() *MockExchangeRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockExchangeRepository) Add(ctx context.Context, exchange domain.ExchangeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, exchange)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockExchangeRepositoryMockRecorder) Add(ctx, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockExchangeRepository)(nil).Add), ctx, exchange)
}

// GetByID mocks base method.
func (m *MockExchangeRepository) GetByID(ctx context.Context, exchangeID uuid.UUID) (domain.ExchangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, exchangeID)
	ret0, _ := ret[0].(domain.ExchangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExchangeRepositoryMockRecorder) GetByID(ctx, exchangeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExchangeRepository)(nil).GetByID), ctx, exchangeID)
}

// GetByOwnedBook mocks base method.
func (m *MockExchangeRepository) GetByOwnedBook(ctx context.Context, ownedBookID uuid.UUID) ([]*domain.ExchangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnedBook", ctx, ownedBookID)
	ret0, _ := ret[0].([]*domain.ExchangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnedBook indicates an expected call of GetByOwnedBook.
func (mr *MockExchangeRepositoryMockRecorder) GetByOwnedBook(ctx, ownedBookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnedBook", reflect.TypeOf((*MockExchangeRepository)(nil).GetByOwnedBook), ctx, ownedBookID)
}

// GetByUserID mocks base method.
func (m *MockExchangeRepository) GetByUserID(ctx context.Context, userID uuid.UUID, status string) ([]*domain.ExchangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, status)
	ret0, _ := ret[0].([]*domain.ExchangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockExchangeRepositoryMockRecorder) GetByUserID(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockExchangeRepository)(nil).GetByUserID), ctx, userID, status)
}

// UpdateStatus mocks base method.
func (m *MockExchangeRepository) UpdateStatus(ctx context.Context, exchangeID uuid.UUID, status domain.ExchangeStatus) (domain.ExchangeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, exchangeID, status)
	ret0, _ := ret[0].(domain.ExchangeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockExchangeRepositoryMockRecorder) UpdateStatus(ctx, exchangeID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockExchangeRepository)(nil).UpdateStatus), ctx, exchangeID, status)
}

// MockOwnedBookRepository is a mock of OwnedBookRepository interface.
type MockOwnedBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOwnedBookRepositoryMockRecorder
	isgomock struct{}
}

// MockOwnedBookRepositoryMockRecorder is the mock recorder for MockOwnedBookRepository.
type MockOwnedBookRepositoryMockRecorder struct {
	mock *MockOwnedBookRepository
}

// NewMockOwnedBookRepository creates a new mock instance.
func NewMockOwnedBookRepository(ctrl *gomock.Controller) *MockOwnedBookRepository {
	mock := &MockOwnedBookRepository{ctrl: ctrl}
	mock.recorder = &MockOwnedBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnedBookRepository) EXPECT() *MockOwnedBookRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOwnedBookRepository) Add(ctx context.Context, ownedBook domain.OwnedBook) (domain.OwnedBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, ownedBook)
	ret0, _ := ret[0].(domain.OwnedBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockOwnedBookRepositoryMockRecorder) Add(ctx, ownedBook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOwnedBookRepository)(nil).Add), ctx, ownedBook)
}

// GetByUserID mocks base method.
func (m *MockOwnedBookRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.OwnedBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.OwnedBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOwnedBookRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOwnedBookRepository)(nil).GetByUserID), ctx, userID)
}

// GetOwnedBook mocks base method.
func (m *MockOwnedBookRepository) GetOwnedBook(ctx context.Context, userID, bookID uuid.UUID) (domain.OwnedBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnedBook", ctx, userID, bookID)
	ret0, _ := ret[0].(domain.OwnedBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedBook indicates an expected call of GetOwnedBook.
func (mr *MockOwnedBookRepositoryMockRecorder) GetOwnedBook(ctx, userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedBook", reflect.TypeOf((*MockOwnedBookRepository)(nil).GetOwnedBook), ctx, userID, bookID)
}

// UpdateStatus mocks base method.
func (m *MockOwnedBookRepository) UpdateStatus(ctx context.Context, ownedBookID uuid.UUID, status domain.OwnedBookStatus) (domain.OwnedBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, ownedBookID, status)
	ret0, _ := ret[0].(domain.OwnedBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOwnedBookRepositoryMockRecorder) UpdateStatus(ctx, ownedBookID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOwnedBookRepository)(nil).UpdateStatus), ctx, ownedBookID, status)
}

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
	isgomock struct{}
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// AddBookReview mocks base method.
func (m *MockReviewRepository) AddBookReview(ctx context.Context, review domain.BookReview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBookReview", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBookReview indicates an expected call of AddBookReview.
func (mr *MockReviewRepositoryMockRecorder) AddBookReview(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBookReview", reflect.TypeOf((*MockReviewRepository)(nil).AddBookReview), ctx, review)
}

// AddUserReview mocks base method.
func (m *MockReviewRepository) AddUserReview(ctx context.Context, review domain.UserReview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserReview", ctx, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserReview indicates an expected call of AddUserReview.
func (mr *MockReviewRepositoryMockRecorder) AddUserReview(ctx, review any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserReview", reflect.TypeOf((*MockReviewRepository)(nil).AddUserReview), ctx, review)
}

// GetBookReviews mocks base method.
func (m *MockReviewRepository) GetBookReviews(ctx context.Context, bookID uuid.UUID) ([]*domain.BookReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookReviews", ctx, bookID)
	ret0, _ := ret[0].([]*domain.BookReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookReviews indicates an expected call of GetBookReviews.
func (mr *MockReviewRepositoryMockRecorder) GetBookReviews(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookReviews", reflect.TypeOf((*MockReviewRepository)(nil).GetBookReviews), ctx, bookID)
}

// GetUserReviews mocks base method.
func (m *MockReviewRepository) GetUserReviews(ctx context.Context, userID uuid.UUID) ([]*domain.UserReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, userID)
	ret0, _ := ret[0].([]*domain.UserReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockReviewRepositoryMockRecorder) GetUserReviews(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockReviewRepository)(nil).GetUserReviews), ctx, userID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRepository) Add(ctx context.Context, login, password string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, login, password)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUserRepositoryMockRecorder) Add(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRepository)(nil).Add), ctx, login, password)
}

// GetAll mocks base method.
func (m *MockUserRepository) GetAll(ctx context.Context) ([]*application.UserRepoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*application.UserRepoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, userID uuid.UUID) (application.UserRepoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(application.UserRepoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, userID)
}

// GetByLogin mocks base method.
func (m *MockUserRepository) GetByLogin(ctx context.Context, login string) (application.UserRepoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(application.UserRepoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserRepositoryMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetByLogin), ctx, login)
}
