//go:build go1.22

// Package bothttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package bothttp

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExchangeRequestStatus.
const (
	ExchangeRequestStatusAccepted  ExchangeRequestStatus = "accepted"
	ExchangeRequestStatusCanceled  ExchangeRequestStatus = "canceled"
	ExchangeRequestStatusCompleted ExchangeRequestStatus = "completed"
	ExchangeRequestStatusPending   ExchangeRequestStatus = "pending"
	ExchangeRequestStatusRejected  ExchangeRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ExchangeRequestStatus enum.
func (e ExchangeRequestStatus) Valid() bool {
	switch e {
	case ExchangeRequestStatusAccepted:
		return true
	case ExchangeRequestStatusCanceled:
		return true
	case ExchangeRequestStatusCompleted:
		return true
	case ExchangeRequestStatusPending:
		return true
	case ExchangeRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for GetMyExchangesParamsStatus.
const (
	GetMyExchangesParamsStatusAccepted  GetMyExchangesParamsStatus = "accepted"
	GetMyExchangesParamsStatusCanceled  GetMyExchangesParamsStatus = "canceled"
	GetMyExchangesParamsStatusCompleted GetMyExchangesParamsStatus = "completed"
	GetMyExchangesParamsStatusPending   GetMyExchangesParamsStatus = "pending"
	GetMyExchangesParamsStatusRejected  GetMyExchangesParamsStatus = "rejected"
)

// Valid indicates whether the value is a known member of the GetMyExchangesParamsStatus enum.
func (e GetMyExchangesParamsStatus) Valid() bool {
	switch e {
	case GetMyExchangesParamsStatusAccepted:
		return true
	case GetMyExchangesParamsStatusCanceled:
		return true
	case GetMyExchangesParamsStatusCompleted:
		return true
	case GetMyExchangesParamsStatusPending:
		return true
	case GetMyExchangesParamsStatusRejected:
		return true
	default:
		return false
	}
}

// Book defines model for Book.
type Book struct {
	ISBN        *string             `json:"ISBN,omitempty"`
	AuthorName  *string             `json:"authorName,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Title       *string             `json:"title,omitempty"`
	Topics      *[]string           `json:"topics,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ExchangeRequest defines model for ExchangeRequest.
type ExchangeRequest struct {
	CreatedAt   *time.Time             `json:"createdAt,omitempty"`
	ExpiresAt   *time.Time             `json:"expiresAt,omitempty"`
	FromId      *openapi_types.UUID    `json:"fromId,omitempty"`
	Id          *openapi_types.UUID    `json:"id,omitempty"`
	Note        *string                `json:"note,omitempty"`
	OwnedBookId *openapi_types.UUID    `json:"ownedBookId,omitempty"`
	Status      *ExchangeRequestStatus `json:"status,omitempty"`
	ToId        *openapi_types.UUID    `json:"toId,omitempty"`
}

// ExchangeRequestStatus defines model for ExchangeRequest.Status.
type ExchangeRequestStatus string

// Review defines model for Review.
type Review struct {
	BookId *openapi_types.UUID `json:"bookId,omitempty"`
	FromId *openapi_types.UUID `json:"fromId,omitempty"`
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Mark   *int                `json:"mark,omitempty"`
	Report *string             `json:"report,omitempty"`
	ToId   *openapi_types.UUID `json:"toId,omitempty"`
}

// User defines model for User.
type User struct {
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Name   *string             `json:"name,omitempty"`
	Rating *float32            `json:"rating,omitempty"`
}

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// GetBooksParams defines parameters for GetBooks.
type GetBooksParams struct {
	Title *string `form:"title,omitempty" json:"title,omitempty"`
	Topic *string `form:"topic,omitempty" json:"topic,omitempty"`
}

// CreateBookJSONBody defines parameters for CreateBook.
type CreateBookJSONBody struct {
	Description *string   `json:"description,omitempty"`
	Isbn        string    `json:"isbn"`
	Title       string    `json:"title"`
	Topics      *[]string `json:"topics,omitempty"`
}

// CreateExchangeJSONBody defines parameters for CreateExchange.
type CreateExchangeJSONBody struct {
	ExpiresAt   *time.Time         `json:"expiresAt,omitempty"`
	Note        *string            `json:"note,omitempty"`
	OwnedBookId openapi_types.UUID `json:"ownedBookId"`
	ToUserId    openapi_types.UUID `json:"toUserId"`
}

// CreateBookReviewJSONBody defines parameters for CreateBookReview.
type CreateBookReviewJSONBody struct {
	BookId openapi_types.UUID `json:"bookId"`
	Mark   int                `json:"mark"`
	Report *string            `json:"report,omitempty"`
}

// CreateUserReviewJSONBody defines parameters for CreateUserReview.
type CreateUserReviewJSONBody struct {
	Mark   int                `json:"mark"`
	Report *string            `json:"report,omitempty"`
	UserId openapi_types.UUID `json:"userId"`
}

// GetMyExchangesParams defines parameters for GetMyExchanges.
type GetMyExchangesParams struct {
	Status *GetMyExchangesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetMyExchangesParamsStatus defines parameters for GetMyExchanges.
type GetMyExchangesParamsStatus string

// AddToLibraryJSONBody defines parameters for AddToLibrary.
type AddToLibraryJSONBody struct {
	BookId openapi_types.UUID `json:"bookId"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody LoginUserJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody CreateBookJSONBody

// CreateExchangeJSONRequestBody defines body for CreateExchange for application/json ContentType.
type CreateExchangeJSONRequestBody CreateExchangeJSONBody

// CreateBookReviewJSONRequestBody defines body for CreateBookReview for application/json ContentType.
type CreateBookReviewJSONRequestBody CreateBookReviewJSONBody

// CreateUserReviewJSONRequestBody defines body for CreateUserReview for application/json ContentType.
type CreateUserReviewJSONRequestBody CreateUserReviewJSONBody

// AddToLibraryJSONRequestBody defines body for AddToLibrary for application/json ContentType.
type AddToLibraryJSONRequestBody AddToLibraryJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Register
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Search and list books
	// (GET /books)
	GetBooks(w http.ResponseWriter, r *http.Request, params GetBooksParams)
	// Add new book to catalog
	// (POST /books)
	CreateBook(w http.ResponseWriter, r *http.Request)
	// Get book details
	// (GET /books/{bookId})
	GetBookByID(w http.ResponseWriter, r *http.Request, bookId openapi_types.UUID)
	// Create exchange request
	// (POST /exchanges)
	CreateExchange(w http.ResponseWriter, r *http.Request)
	// Get exchange details
	// (GET /exchanges/{exchangeId})
	GetExchange(w http.ResponseWriter, r *http.Request, exchangeId openapi_types.UUID)
	// Accept exchange request
	// (PUT /exchanges/{exchangeId}/accept)
	AcceptExchange(w http.ResponseWriter, r *http.Request, exchangeId openapi_types.UUID)
	// Cancel exchange request
	// (PUT /exchanges/{exchangeId}/cancel)
	CancelExchange(w http.ResponseWriter, r *http.Request, exchangeId openapi_types.UUID)
	// Reject exchange request
	// (PUT /exchanges/{exchangeId}/reject)
	RejectExchange(w http.ResponseWriter, r *http.Request, exchangeId openapi_types.UUID)
	// Add book review
	// (POST /reviews/books)
	CreateBookReview(w http.ResponseWriter, r *http.Request)
	// Add user review
	// (POST /reviews/users)
	CreateUserReview(w http.ResponseWriter, r *http.Request)
	// List all users
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Get my exchanges
	// (GET /users/me/exchanges)
	GetMyExchanges(w http.ResponseWriter, r *http.Request, params GetMyExchangesParams)
	// Get my book library
	// (GET /users/me/library)
	GetMyLibrary(w http.ResponseWriter, r *http.Request)
	// Add book to my library
	// (POST /users/me/library)
	AddToLibrary(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBooks operation middleware
func (siw *ServerInterfaceWrapper) GetBooks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBooksParams

	// ------------- Optional query parameter "title" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "title", r.URL.Query(), &params.Title, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title", Err: err})
		return
	}

	// ------------- Optional query parameter "topic" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "topic", r.URL.Query(), &params.Topic, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "topic", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBooks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBook operation middleware
func (siw *ServerInterfaceWrapper) CreateBook(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookByID operation middleware
func (siw *ServerInterfaceWrapper) GetBookByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookId" -------------
	var bookId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "bookId", r.PathValue("bookId"), &bookId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookByID(w, r, bookId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExchange operation middleware
func (siw *ServerInterfaceWrapper) CreateExchange(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExchange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExchange operation middleware
func (siw *ServerInterfaceWrapper) GetExchange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "exchangeId" -------------
	var exchangeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exchangeId", r.PathValue("exchangeId"), &exchangeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exchangeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExchange(w, r, exchangeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptExchange operation middleware
func (siw *ServerInterfaceWrapper) AcceptExchange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "exchangeId" -------------
	var exchangeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exchangeId", r.PathValue("exchangeId"), &exchangeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exchangeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptExchange(w, r, exchangeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelExchange operation middleware
func (siw *ServerInterfaceWrapper) CancelExchange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "exchangeId" -------------
	var exchangeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exchangeId", r.PathValue("exchangeId"), &exchangeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exchangeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelExchange(w, r, exchangeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectExchange operation middleware
func (siw *ServerInterfaceWrapper) RejectExchange(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "exchangeId" -------------
	var exchangeId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exchangeId", r.PathValue("exchangeId"), &exchangeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exchangeId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectExchange(w, r, exchangeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBookReview operation middleware
func (siw *ServerInterfaceWrapper) CreateBookReview(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBookReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUserReview operation middleware
func (siw *ServerInterfaceWrapper) CreateUserReview(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUserReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyExchanges operation middleware
func (siw *ServerInterfaceWrapper) GetMyExchanges(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyExchangesParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyExchanges(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyLibrary operation middleware
func (siw *ServerInterfaceWrapper) GetMyLibrary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyLibrary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddToLibrary operation middleware
func (siw *ServerInterfaceWrapper) AddToLibrary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddToLibrary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.LoginUser)
	m.HandleFunc("POST "+options.BaseURL+"/auth/register", wrapper.RegisterUser)
	m.HandleFunc("GET "+options.BaseURL+"/books", wrapper.GetBooks)
	m.HandleFunc("POST "+options.BaseURL+"/books", wrapper.CreateBook)
	m.HandleFunc("GET "+options.BaseURL+"/books/{bookId}", wrapper.GetBookByID)
	m.HandleFunc("POST "+options.BaseURL+"/exchanges", wrapper.CreateExchange)
	m.HandleFunc("GET "+options.BaseURL+"/exchanges/{exchangeId}", wrapper.GetExchange)
	m.HandleFunc("PUT "+options.BaseURL+"/exchanges/{exchangeId}/accept", wrapper.AcceptExchange)
	m.HandleFunc("PUT "+options.BaseURL+"/exchanges/{exchangeId}/cancel", wrapper.CancelExchange)
	m.HandleFunc("PUT "+options.BaseURL+"/exchanges/{exchangeId}/reject", wrapper.RejectExchange)
	m.HandleFunc("POST "+options.BaseURL+"/reviews/books", wrapper.CreateBookReview)
	m.HandleFunc("POST "+options.BaseURL+"/reviews/users", wrapper.CreateUserReview)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.GetUsers)
	m.HandleFunc("GET "+options.BaseURL+"/users/me/exchanges", wrapper.GetMyExchanges)
	m.HandleFunc("GET "+options.BaseURL+"/users/me/library", wrapper.GetMyLibrary)
	m.HandleFunc("POST "+options.BaseURL+"/users/me/library", wrapper.AddToLibrary)

	return m
}
