// Code generated by MockGen. DO NOT EDIT.
// Source: weather.go
//
// Generated by this command:
//
//	mockgen -source=weather.go -destination=mock/mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	weather "github.com/n1jke/oop-bsuir-2026/laboratory_work-6/models/weather"
	gomock "go.uber.org/mock/gomock"
)

// MockWeatherDataClient is a mock of WeatherDataClient interface.
type MockWeatherDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherDataClientMockRecorder
	isgomock struct{}
}

// MockWeatherDataClientMockRecorder is the mock recorder for MockWeatherDataClient.
type MockWeatherDataClientMockRecorder struct {
	mock *MockWeatherDataClient
}

// NewMockWeatherDataClient creates a new mock instance.
func NewMockWeatherDataClient(ctrl *gomock.Controller) *MockWeatherDataClient {
	mock := &MockWeatherDataClient{ctrl: ctrl}
	mock.recorder = &MockWeatherDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherDataClient) EXPECT() *MockWeatherDataClientMockRecorder {
	return m.recorder
}

// CityCurrentTemperature mocks base method.
func (m *MockWeatherDataClient) CityCurrentTemperature(city string) (weather.CurrentWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CityCurrentTemperature", city)
	ret0, _ := ret[0].(weather.CurrentWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityCurrentTemperature indicates an expected call of CityCurrentTemperature.
func (mr *MockWeatherDataClientMockRecorder) CityCurrentTemperature(city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityCurrentTemperature", reflect.TypeOf((*MockWeatherDataClient)(nil).CityCurrentTemperature), city)
}

// CityForecast mocks base method.
func (m *MockWeatherDataClient) CityForecast(city string) (weather.Forecast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CityForecast", city)
	ret0, _ := ret[0].(weather.Forecast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CityForecast indicates an expected call of CityForecast.
func (mr *MockWeatherDataClientMockRecorder) CityForecast(city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CityForecast", reflect.TypeOf((*MockWeatherDataClient)(nil).CityForecast), city)
}

// LocationCurrentTemperature mocks base method.
func (m *MockWeatherDataClient) LocationCurrentTemperature(lat, lon float64) (weather.CurrentWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationCurrentTemperature", lat, lon)
	ret0, _ := ret[0].(weather.CurrentWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocationCurrentTemperature indicates an expected call of LocationCurrentTemperature.
func (mr *MockWeatherDataClientMockRecorder) LocationCurrentTemperature(lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationCurrentTemperature", reflect.TypeOf((*MockWeatherDataClient)(nil).LocationCurrentTemperature), lat, lon)
}

// LocationForecast mocks base method.
func (m *MockWeatherDataClient) LocationForecast(lat, lon float64) (weather.Forecast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationForecast", lat, lon)
	ret0, _ := ret[0].(weather.Forecast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocationForecast indicates an expected call of LocationForecast.
func (mr *MockWeatherDataClientMockRecorder) LocationForecast(lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationForecast", reflect.TypeOf((*MockWeatherDataClient)(nil).LocationForecast), lat, lon)
}
