// Code generated by MockGen. DO NOT EDIT.
// Source: weather.go
//
// Generated by this command:
//
//	mockgen -source=weather.go -destination=mock/mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWeatherDataClient is a mock of WeatherDataClient interface.
type MockWeatherDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherDataClientMockRecorder
	isgomock struct{}
}

// MockWeatherDataClientMockRecorder is the mock recorder for MockWeatherDataClient.
type MockWeatherDataClientMockRecorder struct {
	mock *MockWeatherDataClient
}

// NewMockWeatherDataClient creates a new mock instance.
func NewMockWeatherDataClient(ctrl *gomock.Controller) *MockWeatherDataClient {
	mock := &MockWeatherDataClient{ctrl: ctrl}
	mock.recorder = &MockWeatherDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherDataClient) EXPECT() *MockWeatherDataClientMockRecorder {
	return m.recorder
}

// LocationCurrentTemperature mocks base method.
func (m *MockWeatherDataClient) LocationCurrentTemperature(lat, lon float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocationCurrentTemperature", lat, lon)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocationCurrentTemperature indicates an expected call of LocationCurrentTemperature.
func (mr *MockWeatherDataClientMockRecorder) LocationCurrentTemperature(lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocationCurrentTemperature", reflect.TypeOf((*MockWeatherDataClient)(nil).LocationCurrentTemperature), lat, lon)
}
