// Code generated by MockGen. DO NOT EDIT.
// Source: order_logistic.go
//
// Generated by this command:
//
//	mockgen -source=order_logistic.go -destination=mocks/mock.go -package=mocks StockRepository,OrderRequestSource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	application "github.com/n1jke/oop-bsuir-2025/laboratory_work-4/internal/application"
	domain "github.com/n1jke/oop-bsuir-2025/laboratory_work-4/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
	isgomock struct{}
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// LoadCargoInfo mocks base method.
func (m *MockStockRepository) LoadCargoInfo() ([]domain.CargoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCargoInfo")
	ret0, _ := ret[0].([]domain.CargoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCargoInfo indicates an expected call of LoadCargoInfo.
func (mr *MockStockRepositoryMockRecorder) LoadCargoInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCargoInfo", reflect.TypeOf((*MockStockRepository)(nil).LoadCargoInfo))
}

// LoadTransportInfo mocks base method.
func (m *MockStockRepository) LoadTransportInfo() ([]domain.TransportInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTransportInfo")
	ret0, _ := ret[0].([]domain.TransportInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTransportInfo indicates an expected call of LoadTransportInfo.
func (mr *MockStockRepositoryMockRecorder) LoadTransportInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTransportInfo", reflect.TypeOf((*MockStockRepository)(nil).LoadTransportInfo))
}

// MockOrderRequestSource is a mock of OrderRequestSource interface.
type MockOrderRequestSource struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRequestSourceMockRecorder
	isgomock struct{}
}

// MockOrderRequestSourceMockRecorder is the mock recorder for MockOrderRequestSource.
type MockOrderRequestSourceMockRecorder struct {
	mock *MockOrderRequestSource
}

// NewMockOrderRequestSource creates a new mock instance.
func NewMockOrderRequestSource(ctrl *gomock.Controller) *MockOrderRequestSource {
	mock := &MockOrderRequestSource{ctrl: ctrl}
	mock.recorder = &MockOrderRequestSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRequestSource) EXPECT() *MockOrderRequestSourceMockRecorder {
	return m.recorder
}

// RequestOrder mocks base method.
func (m *MockOrderRequestSource) RequestOrder(cargo []domain.CargoInfo, transport []domain.TransportInfo) (*application.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestOrder", cargo, transport)
	ret0, _ := ret[0].(*application.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOrder indicates an expected call of RequestOrder.
func (mr *MockOrderRequestSourceMockRecorder) RequestOrder(cargo, transport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOrder", reflect.TypeOf((*MockOrderRequestSource)(nil).RequestOrder), cargo, transport)
}
